### ISSUE TITLE
Does syntax highlighting work with sublime text 3?

### ISSUE THREAD

**Issue by hunterloftis** [reactjs/sublime-react#1]
(because it isn't for me)

it's installed:

![screen shot 2014-02-25 at 11 00 20 am](https://f.cloud.github.com/assets/364501/2261456/1dfb79c2-9e4f-11e3-9d32-8538e7a38495.png)

and snippets are there:

![screen shot 2014-02-25 at 11 00 55 am](https://f.cloud.github.com/assets/364501/2261463/2e6b78ac-9e4f-11e3-8926-b1ebcfe6b59a.png)

but syntax highlighting for JSX isn't there:

![screen shot 2014-02-25 at 11 01 43 am](https://f.cloud.github.com/assets/364501/2261470/4ae63b5c-9e4f-11e3-85ed-07da2f502df6.png)

**Comment by MBuffenoir** [comment]
I have the same issue ... Snippets are present but no syntax hightliting.
