### ISSUE TITLE
Comments in-between props

### ISSUE THREAD

**Issue by mathieumg** [reactjs/sublime-react#11]
I know not everything is possible since JSX is not a regular language, but currently when using comments in-between props when inserting a component, they don't get highlighted as comments, no matter how they are used:

![Prop comments in Sublime](https://i.imgur.com/gE4JX83.png)

According to the [docs](https://facebook.github.io/react/docs/jsx-in-depth.html#comments), these are accepted (and do indeed work). When highlighted, comments usually take a different color (grey in my case, with Monokai), here they seem to be treated as props.

I was wondering if there was any way around that or if it's a known limitation, thank you!

**Comment by mathieumg** [comment]
Am I wrong thinking this has been fixed by recent commits?

**Comment by zertosh** [comment]
@mathieumg babel-sublime has that fixed https://github.com/babel/babel-sublime

**Comment by mathieumg** [comment]
@zertosh I know I'm using it, but thanks! :smile:  I wanted to know if it was relevant to close it for this repo.

**Comment by jgebhardt** [comment]
This package no longer provides syntax highlighting. Please install the "Babel" package for syntax highlighting instead.
