### ISSUE TITLE
Support ES6 ": function"-less notation

### ISSUE THREAD

**Issue by gaearon** [reactjs/sublime-react#16]
I'd like to bring https://github.com/yungsters/sublime/issues/5 to your attention in case it doesn't get noticed. There are two stale pull requests in the repo so I'm not sure if it is maintained at all.

The problem arises when using React with harmony transforms: short method notation is unreadable because method names aren't highlighted:

![](https://camo.githubusercontent.com/1065344327c447e3ac50442114e6b06804e7fd7c/687474703a2f2f692e696d6775722e636f6d2f624146625a68662e706e67)

I submitted a [pull request](https://github.com/yungsters/sublime/pull/6) to JSX tmLanguage which, albeit hackish, gets the job done and tries very hard to not introduce false positives.

![](http://i.imgur.com/RMKPOSu.png)

Hope it is helpful to you as it was to me.

**Comment by gaearon** [comment]
>IMO it's better to just rebase this project on top of JavaScriptNext and work from there so we get all the new stuff.

Yeah that's what these folks did. It works perfectly:

https://github.com/6to5/6to5-sublime

**Comment by jgebhardt** [comment]
This package no longer provides syntax highlighting. Please install the "Babel" package for syntax highlighting instead.
