### ISSUE TITLE
Work together with Emmet

### ISSUE THREAD

**Issue by kaddopur** [reactjs/sublime-react#21]
I've tried to add the following key binding for Emmet, and it doesn't seem to work.
This snippet is from another packag, [JSX](https://github.com/allanhortle/JSX).

How do I turn this on?

```
{
    "keys": ["tab"],
    "command": "expand_abbreviation_by_tab", 
    "context": [
        {
            "operand": "source.js.jsx", 
            "operator": "equal", 
            "match_all": true, 
            "key": "selector"
        }
    ]
}
```

**Comment by max-mykhailenko** [comment]
Look at my gist https://gist.github.com/max-mykhailenko/41d0c3991d92f38dcbc6

**Comment by burtyish** [comment]
Can you explain how to enable emmet for .cjsx files?

**Comment by jgebhardt** [comment]
@max-mykhailenko: This seems pretty specific to emmet users and not necessarily something that all sublime-react users might be interested in. I'm going to close this for now in favor of people using your custom config, if needed. I'd be happy to be convinced otherwise.
