### ISSUE TITLE
The word "get" messes up syntax highlighting.

### ISSUE THREAD

**Issue by btholt** [reactjs/sublime-react#23]
Try the following in Sublime:

```javascript
var Test = React.createClass({

  render: function() {
    return (
      <div>
        <h1>
          I want to get out of here.
        </h1>
      </div>
    );
  }

});
```

Notice it messes up the syntax highlighting of `</h1>` and `</div>`. Try taking out the word "get" and it works okay again.

**Comment by jgebhardt** [comment]
This package no longer provides syntax highlighting. Please install the "Babel" package for syntax highlighting instead.
