### ISSUE TITLE
Harmony (ES6) Syntax Highlighting

### ISSUE THREAD

**Issue by appsforartists** [reactjs/sublime-react#24]
I use [jsx-loader](https://github.com/petehunt/jsx-loader) to enable Harmony syntax in my JS files (even the ones that aren't in JSX).  The JSX syntax highlighter is pretty nice for ES5 and JSX, but doesn't seem to highlight lambda arrows or interpolated strings.

Can we fix that in this repo?

**Comment by Dashed** [comment]
Wondering about this as well. @jgebhardt's suggestion sounds appealing and probably put it under 6to5 umbrella; since 6to5 supports JSX. Will look into this when I have time.

**Comment by gaearon** [comment]
FYI https://github.com/6to5/6to5-sublime is built on top of JavaScriptNext and supports both ES6 and JSX.
