### ISSUE TITLE
Treat parens after return like curly braces after function

### ISSUE THREAD

**Issue by ClimbsRocks** [reactjs/sublime-react#36]
Right now, when you type in the parens after a return statement inside of a render function, it doesn't know how to handle the indentation intelligently. 

Example of unintelligent return parens behavior: 
![image](https://cloud.githubusercontent.com/assets/7017045/5933020/d9071d94-a66d-11e4-9073-42c3028110c7.png)

It would be awesome if these parens could be handled like the curly braces after function(): 
![image](https://cloud.githubusercontent.com/assets/7017045/5933033/2e067628-a66e-11e4-9425-da158ce77c6e.png)

In this case, by just hitting the enter button once while in between the curly braces, it automatically does three things: 

1. takes the cursor one line down
2. indents the cursor one level of indentation
3. puts the curly brace two lines down, and at the correct level of indentation

If the parens after the return statement inside of a render function could behave this same way, that would be awesome!

**Comment by jgebhardt** [comment]
This package no longer provides syntax highlighting. Please install the "Babel" package for syntax highlighting instead.
