### ISSUE TITLE
Syntax support for ES6 Harmony?

### ISSUE THREAD

**Issue by frostyandy2k** [reactjs/sublime-react#37]
Will there be any support for the ES6 syntax like methods without the "function" keyword

<code>
method(){
 //do something
}
</code>

The JSX compiler supports many ES6 features and syntax highlighting would be awesome.

**Comment by jwarkentin** [comment]
+1

**Comment by zertosh** [comment]
@jwarkentin Check out https://github.com/babel/babel-sublime#screenshots

**Comment by jwarkentin** [comment]
Thanks! That's awesome!

**Comment by jgebhardt** [comment]
This package no longer provides syntax highlighting. Please install the "Babel" package for syntax highlighting instead.
