### ISSUE TITLE
Close tag command not working in CoffeeScript

### ISSUE THREAD

**Issue by noinkling** [reactjs/sublime-react#39]
Using the "close tag" command (`alt + .` in Windows) works fine for JSX in JS files, but not in CoffeeScript files. I have the syntax set correctly.

Comparing the scopes, the main difference seems to be that tags in JS get given `tag.open.js` or `tag.close.js` labels, while in CoffeeScript they don't receive an equivalent. Looking through the CoffeeScript `.tmLanguage` file, it looks like they should be getting `tag.open.coffee` and `tag.close.coffee` (but aren't). Also the opening bracket itself is getting `punctuation.definition.tag.begin.coffee`, but the closing one isn't getting its equivalent, which seems to be related.

**Edit:**
Removing the whole `jsx-tag-area` key seems to fix it - the tags then get their proper scopes and the close tag command works. It looks like they are being overriden by `jsx.tag-area.coffee` instead, and each level of JSX nesting seems to be adding duplicates of this scope.

**Update:**
Actually the syntax highlighting tends to break pretty badly overall at some point in longer files with a decent amount of JSX (i.e. once too many duplicate `jsx.tag-area.coffee` scopes appear at the same place). Likely related to #40.

/cc @tgriesser

**Comment by jgebhardt** [comment]
This package no longer provides syntax highlighting, and has been superseded by the babel/babel-sublime package.
Since Babel unfortunately does not support CoffeeScript, I recommend that someone set up a new repo+package to maintain CoffeeScript separately (it could be you! :)
Thank you for your understanding.

**Comment by binarykitchen** [comment]
i understand
