### ISSUE TITLE
Syntax highlighting (CJSX) breaks when having a self-closing components or attributes over multiple lines

### ISSUE THREAD

**Issue by jenskanis** [reactjs/sublime-react#42]
Until very recently the syntax highlighting was perfect. But now it's breaking on the following code:

![screen shot 2015-02-24 at 14 05 17](https://cloud.githubusercontent.com/assets/1345437/6349795/613e13ea-bc2e-11e4-9120-cf6b3c4d5ff7.png)

Notice the white `render` function. We can only make this work if we place the attributes all on a single line or add a component closing tag:

![screen shot 2015-02-24 at 14 05 52](https://cloud.githubusercontent.com/assets/1345437/6349823/a3a82a9a-bc2e-11e4-87cd-731d9465b0f6.png)

![screen shot 2015-02-24 at 14 05 30](https://cloud.githubusercontent.com/assets/1345437/6349828/a6ff84c2-bc2e-11e4-8100-7469f2a7e3b7.png)

I think the closing tag is pretty ugly because I don't have children defined in the sub component and our linter isn't very happy with the long lines when placing all attributes on the same line.

**Comment by erlingwl** [comment]
We are experiencing the exact same issue - seems like a regression from the latest update.

**Comment by littletimo** [comment]
+1 I'm seeing this as well...

**Comment by jenskanis** [comment]
Anybody knows what caused this bug?

**Comment by moelee** [comment]
+1

**Comment by jgebhardt** [comment]
This package no longer provides syntax highlighting, and has been superseded by the babel/babel-sublime package.
Since Babel unfortunately does not support CoffeeScript, I recommend that someone set up a new repo+package to maintain CoffeeScript separately (it could be you! :)
Thank you for your understanding.
