### ISSUE TITLE
JavaScript (JSX) syntax breaks autocompletions

### ISSUE THREAD

**Issue by durz** [reactjs/sublime-react#44]
When JavaScript (JSX) is used as the active syntax, autocompletion always shows "No available completion".

![jsx](https://cloud.githubusercontent.com/assets/4900094/7082297/207d1eca-df95-11e4-8a29-7a3cca2b847b.jpg)

When regular JavaScript is used as the syntax, autocompletions work as expected.

![js](https://cloud.githubusercontent.com/assets/4900094/7082289/f5d39c62-df94-11e4-8bbb-0070221c6e3a.jpg)

**Comment by jgebhardt** [comment]
This package no longer provides syntax highlighting. Please install the "Babel" package for syntax highlighting instead.
