### ISSUE TITLE
Restore CJSX syntax highlighting

### ISSUE THREAD

**Issue by morleyzhi** [reactjs/sublime-react#47]
The latest release deprecated syntax highlighting in favor of Babel's:

https://github.com/reactjs/sublime-react/releases/tag/v0.2.0

Unfortunately, this broke Coffeescript JSX syntax highlighting, which Babel obviously doesn't support, and for which there's no real replacement. Can we restore syntax highlighting for that use case, or provide a better solution?

Thanks!

**Comment by zertosh** [comment]
@morleyzhi It seems that the CJSX is taking care of this https://github.com/babel/babel-sublime/issues/96#issuecomment-95252964

**Comment by morleyzhi** [comment]
Oh great. Thanks!
